on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
    types: [opened, synchronize, reopened]
jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "worked"
